using CommunityToolkit.Mvvm.ComponentModel;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace KHMPartiturenCentrum.Models;

public class SaveScoreModel
{
    public int AccompanimentChanged = 0;
    public int AccompanimentId = 0;
    public int AmountPublisher1 = 0;
    public int AmountPublisher1Changed = 0;
    public int AmountPublisher2 = 0;
    public int AmountPublisher2Changed = 0;
    public int AmountPublisher3 = 0;
    public int AmountPublisher3Changed = 0;
    public int AmountPublisher4 = 0;
    public int AmountPublisher4Changed = 0;
    public int ArchiveChanged = 0;
    public int ArchiveId = 0;
    public int ArrangerChanged = 0;
    public int ByHeart= 0;
    public int Checked = 0;
    public int ComposerChanged = 0;
    public int DateDigitizedChanged = 0;
    public int DateModifiedChanged = 0;
    public int GenreChanged = 0;
    public int GenreId = 0;
    public int LanguageChanged = 0;
    public int LanguageId = 0;
    public int LyricsChanged = 0;
    public int MP3B1= 0;
    public int MP3B2= 0;
    public int MP3PIA= 0;
    public int MP3SOL= 0;
    public int MP3T1= 0;
    public int MP3T2= 0;
    public int MP3TOT= 0;
    public int MuseScoreOnline= 0;
    public int MuseScoreORK= 0;
    public int MuseScoreORP= 0;
    public int MuseScoreTOK= 0;
    public int MuseScoreTOP= 0;
    public int MusicPieceChanged = 0;
    public int NotesChanged = 0;
    public int NumberScoresTotal = 0;
    public int PDFORK= 0;
    public int PDFORP= 0;
    public int PDFTOK= 0;
    public int PDFTOP= 0;
    public int Publisher1Changed = 0;
    public int Publisher1Id = 0;
    public int Publisher2Changed = 0;
    public int Publisher2Id = 0;
    public int Publisher3Changed = 0;
    public int Publisher3Id = 0;
    public int Publisher4Changed = 0;
    public int Publisher4Id = 0;
    public int RepertoireChanged = 0;
    public int RepertoireId = 0;
    public int ScoreId = 0;
    public int SubTitleChanged = 0;
    public int TextwriterChanged = 0;
    public int TitleChanged = 0;
    public string AccompanimentName = "";
    public string ArchiveName = "";
    public string Arranger = "";
    public string Composer = "";
    public string DateDigitized = "";
    public string DateModified = "";
    public string GenreName = "";
    public string LanguageName = "";
    public string Lyrics = "";
    public string MusicPiece = "";
    public string Notes = "";
    public string Publisher1Name = "";
    public string Publisher2Name = "";
    public string Publisher3Name = "";
    public string Publisher4Name = "";
    public string RepertoireName = "";
    public string ScoreMainNumber = "";
    public string ScoreNumber = "";
    public string ScoreSubNumber = "";
    public string SubTitle = "";
    public string Textwriter = "";
    public string Title = "";
}
